[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
foundersnet = "62zGLQRxEiWwLrovAiABVcnqvMjGiSkBdyNyhKJqy5Qj"

[programs.localnet]
foundersnet = "62zGLQRxEiWwLrovAiABVcnqvMjGiSkBdyNyhKJqy5Qj"

[programs.mainnet]
foundersnet = "62zGLQRxEiWwLrovAiABVcnqvMjGiSkBdyNyhKJqy5Qj"

[programs.testnet]
foundersnet = "62zGLQRxEiWwLrovAiABVcnqvMjGiSkBdyNyhKJqy5Qj"